export const LIST = [
	{
		id: 1,
		name: "Ahmad ke satu",
		email: "ahmad1@gmail.com",
		totalTask: 3,
		meanRating: 7.5,
		maxRating: 10,
		detail: [
			{
				id: 1,
				activityName: "Aktivitas 1",
				activityPlace: "Jakarta",
				activityDescription: "di mampang",
				activityDateStart: "2021-08-25",
				activityDateEnd: "2021-08-31",
				activityDetail: "Deatil",
				activityTimeEnd: "17:05:04",
				activityTimeStart: "17:05:04",
				rating: 7.5,
			},
			{
				id: 2,
				activityName: "Aktivitas 2",
				activityPlace: "Jakarta",
				activityDescription: "di mampang",
				activityDateStart: "2021-08-25",
				activityDateEnd: "2021-08-31",
				activityDetail: "Deatil",
				activityTimeEnd: "17:05:04",
				activityTimeStart: "17:05:04",
				rating: 7.5,
			},
			{
				id: 3,
				activityName: "Aktivitas 3",
				activityPlace: "Jakarta",
				activityDescription: "di mampang",
				activityDateStart: "2021-08-25",
				activityDateEnd: "2021-08-31",
				activityTimeEnd: "17:05:04",
				activityTimeStart: "17:05:04",
				activityDetail: "Deatil",
				rating: 7.5,
			},
		],
	},
];
