export const campaignList = {
	GetShopCriteria: {
		shop_criteria: [
			{
				id: 1,
				name: "Agenda 1",
				detail: "Gedung DPRD",
				startDate: "08-09-2021 10:22:00",
				endDate: "08-10-2021 10:22:00",
				location: "Jakarta",
				description: "rapat penting paripurna",
				coordinator: { value: "koor 1", label: "Koor 1" },
				notes: "keterangan here",
				status: { value: "Diagendakan", label: "Diagendakan" },
				protocols: [
					{ value: "pro 1", label: "pro 1" },
					{ value: "pro 2", label: "pro 2" },
				],
				audiences: [
					{ value: "peserta 1", label: "peserta 1" },
					{ value: "peserta 2", label: "peserta 2" },
				],
			},
			{
				id: 2,
				name: "Agenda 2",
				detail: "Gedung DPRD",
				startDate: "08-09-2021 10:22:00",
				endDate: "08-10-2021 10:22:00",
				location: "Jakarta",
				description: "rapat penting paripurna",
				coordinator: { value: "koor 1", label: "Koor 1" },
				notes: "keterangan here",
				status: { value: "Diagendakan", label: "Diagendakan" },
				protocols: [{ value: "pro 1", label: "pro 1" }],
				audiences: [
					{ value: "peserta 1", label: "peserta 1" },
					{ value: "peserta 2", label: "peserta 2" },
				],
			},
			{
				id: 3,
				name: "Agenda 3",
				detail: "Gedung DPRD",
				startDate: "08-09-2021 10:22:00",
				endDate: "08-10-2021 10:22:00",
				location: "Jakarta",
				description: "rapat penting paripurna",
				coordinator: { value: "koor 1", label: "Koor 1" },
				protocols: [{ value: "pro 1", label: "pro 1" }],
				notes: "keterangan here",
				status: { value: "Diagendakan", label: "Diagendakan" },
				audiences: [
					{ value: "peserta 1", label: "peserta 1" },
					{ value: "peserta 2", label: "peserta 2" },
				],
			},
			{
				id: 4,
				name: "Agenda 4",
				detail: "Gedung DPRD",
				startDate: "08-09-2021 10:22:00",
				endDate: "08-10-2021 10:22:00",
				location: "Jakarta",
				description: "rapat penting paripurna",
				coordinator: { value: "koor 1", label: "Koor 1" },
				protocols: [{ value: "pro 1", label: "pro 1" }],
				notes: "keterangan here",
				status: { value: "Diagendakan", label: "Diagendakan" },
				audiences: [
					{ value: "peserta 1", label: "peserta 1" },
					{ value: "peserta 2", label: "peserta 2" },
				],
			},
		],
		total_data: 100,
		response_header: {
			success: true,
		},
	},
};
